jobs:
  - job: TagBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - download: MonorepoBuildResources
        artifact: AppBuilds
        displayName: Download Monorepo Build Version
        patterns: |
          version.json
      - script: |
          echo "##vso[task.setvariable variable=buildVersion]$(jq -r .buildVersion $(Pipeline.Workspace)/MonorepoBuildResources/AppBuilds/version.json)"
        displayName: Get buildVersion from version.json
      - script: |
          echo "##vso[build.updatebuildnumber]$(Build.BuildNumber)_$(buildVersion)"
          echo "##vso[build.addbuildtag]$(buildVersion)"